### ISSUE TITLE
`parameter_sweep` and `box_plot_max_weekly_cases` functions

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/ringbp#61]
It is questionable whether these should live in the package - especially the plotting one might be better suited to the paper repo, but I've kept it here for now as it's got the general parameter syntax etc. which the figures functions did not.

**Comment by sbfnk** [comment]
@sophiemeakin I see that you have these functions in `{pepbp}`. Did you use them at all?

**Comment by sophiemeakin** [comment]
I included a very similar `parameter_sweep` function, where the only real difference was the parameters that were passed. If you were to remove `parameter_sweep` from the package, I'd suggest adding a nice vignette where you use it - so that the code is still there, even if not a function in the package.
I didn't include any plotting functions, and agree that they probably are better suited to analysis repos, rather than packages.
